version: "3.8"
services:
    app:
      extends: 
        file: docker-compose-generic.yml
        service: app

    nginx:
          extends: 
            file: docker-compose-generic.yml
            service: nginx
          depends_on:
              - app
